/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardSidebarLayoutImport } from './routes/dashboard/_sidebarLayout'
import { Route as DashboardSidebarLayoutIndexImport } from './routes/dashboard/_sidebarLayout/index'
import { Route as DashboardSidebarLayoutCategoryImport } from './routes/dashboard/_sidebarLayout/category'
import { Route as DashboardSidebarLayoutProductIndexImport } from './routes/dashboard/_sidebarLayout/product/index'
import { Route as DashboardSidebarLayoutUserEmployeeImport } from './routes/dashboard/_sidebarLayout/user/employee'
import { Route as DashboardSidebarLayoutUserCustomerImport } from './routes/dashboard/_sidebarLayout/user/customer'
import { Route as DashboardSidebarLayoutUserCreateImport } from './routes/dashboard/_sidebarLayout/user/create'
import { Route as DashboardSidebarLayoutProductCreateImport } from './routes/dashboard/_sidebarLayout/product/create'
import { Route as DashboardSidebarLayoutUserUpdateUserIdImport } from './routes/dashboard/_sidebarLayout/user/update.$userId'
import { Route as DashboardSidebarLayoutProductUpdateProductIdImport } from './routes/dashboard/_sidebarLayout/product/update.$productId'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()
const authResetPasswordLazyImport = createFileRoute('/(auth)/reset-password')()
const authRegisterLazyImport = createFileRoute('/(auth)/register')()
const authLoginLazyImport = createFileRoute('/(auth)/login')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordLazyRoute = authResetPasswordLazyImport
  .update({
    id: '/(auth)/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/reset-password.lazy').then((d) => d.Route),
  )

const authRegisterLazyRoute = authRegisterLazyImport
  .update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/register.lazy').then((d) => d.Route))

const authLoginLazyRoute = authLoginLazyImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const DashboardSidebarLayoutRoute = DashboardSidebarLayoutImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSidebarLayoutIndexRoute =
  DashboardSidebarLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutCategoryRoute =
  DashboardSidebarLayoutCategoryImport.update({
    id: '/category',
    path: '/category',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutProductIndexRoute =
  DashboardSidebarLayoutProductIndexImport.update({
    id: '/product/',
    path: '/product/',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutUserEmployeeRoute =
  DashboardSidebarLayoutUserEmployeeImport.update({
    id: '/user/employee',
    path: '/user/employee',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutUserCustomerRoute =
  DashboardSidebarLayoutUserCustomerImport.update({
    id: '/user/customer',
    path: '/user/customer',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutUserCreateRoute =
  DashboardSidebarLayoutUserCreateImport.update({
    id: '/user/create',
    path: '/user/create',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutProductCreateRoute =
  DashboardSidebarLayoutProductCreateImport.update({
    id: '/product/create',
    path: '/product/create',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutUserUpdateUserIdRoute =
  DashboardSidebarLayoutUserUpdateUserIdImport.update({
    id: '/user/update/$userId',
    path: '/user/update/$userId',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

const DashboardSidebarLayoutProductUpdateProductIdRoute =
  DashboardSidebarLayoutProductUpdateProductIdImport.update({
    id: '/product/update/$productId',
    path: '/product/update/$productId',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_sidebarLayout': {
      id: '/dashboard/_sidebarLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardSidebarLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_sidebarLayout/category': {
      id: '/dashboard/_sidebarLayout/category'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardSidebarLayoutCategoryImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/': {
      id: '/dashboard/_sidebarLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardSidebarLayoutIndexImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/product/create': {
      id: '/dashboard/_sidebarLayout/product/create'
      path: '/product/create'
      fullPath: '/dashboard/product/create'
      preLoaderRoute: typeof DashboardSidebarLayoutProductCreateImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/user/create': {
      id: '/dashboard/_sidebarLayout/user/create'
      path: '/user/create'
      fullPath: '/dashboard/user/create'
      preLoaderRoute: typeof DashboardSidebarLayoutUserCreateImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/user/customer': {
      id: '/dashboard/_sidebarLayout/user/customer'
      path: '/user/customer'
      fullPath: '/dashboard/user/customer'
      preLoaderRoute: typeof DashboardSidebarLayoutUserCustomerImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/user/employee': {
      id: '/dashboard/_sidebarLayout/user/employee'
      path: '/user/employee'
      fullPath: '/dashboard/user/employee'
      preLoaderRoute: typeof DashboardSidebarLayoutUserEmployeeImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/product/': {
      id: '/dashboard/_sidebarLayout/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardSidebarLayoutProductIndexImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/product/update/$productId': {
      id: '/dashboard/_sidebarLayout/product/update/$productId'
      path: '/product/update/$productId'
      fullPath: '/dashboard/product/update/$productId'
      preLoaderRoute: typeof DashboardSidebarLayoutProductUpdateProductIdImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
    '/dashboard/_sidebarLayout/user/update/$userId': {
      id: '/dashboard/_sidebarLayout/user/update/$userId'
      path: '/user/update/$userId'
      fullPath: '/dashboard/user/update/$userId'
      preLoaderRoute: typeof DashboardSidebarLayoutUserUpdateUserIdImport
      parentRoute: typeof DashboardSidebarLayoutImport
    }
  }
}

// Create and export the route tree

interface DashboardSidebarLayoutRouteChildren {
  DashboardSidebarLayoutCategoryRoute: typeof DashboardSidebarLayoutCategoryRoute
  DashboardSidebarLayoutIndexRoute: typeof DashboardSidebarLayoutIndexRoute
  DashboardSidebarLayoutProductCreateRoute: typeof DashboardSidebarLayoutProductCreateRoute
  DashboardSidebarLayoutUserCreateRoute: typeof DashboardSidebarLayoutUserCreateRoute
  DashboardSidebarLayoutUserCustomerRoute: typeof DashboardSidebarLayoutUserCustomerRoute
  DashboardSidebarLayoutUserEmployeeRoute: typeof DashboardSidebarLayoutUserEmployeeRoute
  DashboardSidebarLayoutProductIndexRoute: typeof DashboardSidebarLayoutProductIndexRoute
  DashboardSidebarLayoutProductUpdateProductIdRoute: typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  DashboardSidebarLayoutUserUpdateUserIdRoute: typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}

const DashboardSidebarLayoutRouteChildren: DashboardSidebarLayoutRouteChildren =
  {
    DashboardSidebarLayoutCategoryRoute: DashboardSidebarLayoutCategoryRoute,
    DashboardSidebarLayoutIndexRoute: DashboardSidebarLayoutIndexRoute,
    DashboardSidebarLayoutProductCreateRoute:
      DashboardSidebarLayoutProductCreateRoute,
    DashboardSidebarLayoutUserCreateRoute:
      DashboardSidebarLayoutUserCreateRoute,
    DashboardSidebarLayoutUserCustomerRoute:
      DashboardSidebarLayoutUserCustomerRoute,
    DashboardSidebarLayoutUserEmployeeRoute:
      DashboardSidebarLayoutUserEmployeeRoute,
    DashboardSidebarLayoutProductIndexRoute:
      DashboardSidebarLayoutProductIndexRoute,
    DashboardSidebarLayoutProductUpdateProductIdRoute:
      DashboardSidebarLayoutProductUpdateProductIdRoute,
    DashboardSidebarLayoutUserUpdateUserIdRoute:
      DashboardSidebarLayoutUserUpdateUserIdRoute,
  }

const DashboardSidebarLayoutRouteWithChildren =
  DashboardSidebarLayoutRoute._addFileChildren(
    DashboardSidebarLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardSidebarLayoutRoute: typeof DashboardSidebarLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSidebarLayoutRoute: DashboardSidebarLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardSidebarLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/reset-password': typeof authResetPasswordLazyRoute
  '/dashboard/category': typeof DashboardSidebarLayoutCategoryRoute
  '/dashboard/': typeof DashboardSidebarLayoutIndexRoute
  '/dashboard/product/create': typeof DashboardSidebarLayoutProductCreateRoute
  '/dashboard/user/create': typeof DashboardSidebarLayoutUserCreateRoute
  '/dashboard/user/customer': typeof DashboardSidebarLayoutUserCustomerRoute
  '/dashboard/user/employee': typeof DashboardSidebarLayoutUserEmployeeRoute
  '/dashboard/product': typeof DashboardSidebarLayoutProductIndexRoute
  '/dashboard/product/update/$productId': typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  '/dashboard/user/update/$userId': typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardSidebarLayoutIndexRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/reset-password': typeof authResetPasswordLazyRoute
  '/dashboard/category': typeof DashboardSidebarLayoutCategoryRoute
  '/dashboard/product/create': typeof DashboardSidebarLayoutProductCreateRoute
  '/dashboard/user/create': typeof DashboardSidebarLayoutUserCreateRoute
  '/dashboard/user/customer': typeof DashboardSidebarLayoutUserCustomerRoute
  '/dashboard/user/employee': typeof DashboardSidebarLayoutUserEmployeeRoute
  '/dashboard/product': typeof DashboardSidebarLayoutProductIndexRoute
  '/dashboard/product/update/$productId': typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  '/dashboard/user/update/$userId': typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_sidebarLayout': typeof DashboardSidebarLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/login': typeof authLoginLazyRoute
  '/(auth)/register': typeof authRegisterLazyRoute
  '/(auth)/reset-password': typeof authResetPasswordLazyRoute
  '/dashboard/_sidebarLayout/category': typeof DashboardSidebarLayoutCategoryRoute
  '/dashboard/_sidebarLayout/': typeof DashboardSidebarLayoutIndexRoute
  '/dashboard/_sidebarLayout/product/create': typeof DashboardSidebarLayoutProductCreateRoute
  '/dashboard/_sidebarLayout/user/create': typeof DashboardSidebarLayoutUserCreateRoute
  '/dashboard/_sidebarLayout/user/customer': typeof DashboardSidebarLayoutUserCustomerRoute
  '/dashboard/_sidebarLayout/user/employee': typeof DashboardSidebarLayoutUserEmployeeRoute
  '/dashboard/_sidebarLayout/product/': typeof DashboardSidebarLayoutProductIndexRoute
  '/dashboard/_sidebarLayout/product/update/$productId': typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  '/dashboard/_sidebarLayout/user/update/$userId': typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/category'
    | '/dashboard/'
    | '/dashboard/product/create'
    | '/dashboard/user/create'
    | '/dashboard/user/customer'
    | '/dashboard/user/employee'
    | '/dashboard/product'
    | '/dashboard/product/update/$productId'
    | '/dashboard/user/update/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/category'
    | '/dashboard/product/create'
    | '/dashboard/user/create'
    | '/dashboard/user/customer'
    | '/dashboard/user/employee'
    | '/dashboard/product'
    | '/dashboard/product/update/$productId'
    | '/dashboard/user/update/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/_sidebarLayout'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/dashboard/_sidebarLayout/category'
    | '/dashboard/_sidebarLayout/'
    | '/dashboard/_sidebarLayout/product/create'
    | '/dashboard/_sidebarLayout/user/create'
    | '/dashboard/_sidebarLayout/user/customer'
    | '/dashboard/_sidebarLayout/user/employee'
    | '/dashboard/_sidebarLayout/product/'
    | '/dashboard/_sidebarLayout/product/update/$productId'
    | '/dashboard/_sidebarLayout/user/update/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authLoginLazyRoute: typeof authLoginLazyRoute
  authRegisterLazyRoute: typeof authRegisterLazyRoute
  authResetPasswordLazyRoute: typeof authResetPasswordLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authLoginLazyRoute: authLoginLazyRoute,
  authRegisterLazyRoute: authRegisterLazyRoute,
  authResetPasswordLazyRoute: authResetPasswordLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/register",
        "/(auth)/reset-password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_sidebarLayout"
      ]
    },
    "/dashboard/_sidebarLayout": {
      "filePath": "dashboard/_sidebarLayout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_sidebarLayout/category",
        "/dashboard/_sidebarLayout/",
        "/dashboard/_sidebarLayout/product/create",
        "/dashboard/_sidebarLayout/user/create",
        "/dashboard/_sidebarLayout/user/customer",
        "/dashboard/_sidebarLayout/user/employee",
        "/dashboard/_sidebarLayout/product/",
        "/dashboard/_sidebarLayout/product/update/$productId",
        "/dashboard/_sidebarLayout/user/update/$userId"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.lazy.tsx"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.lazy.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.lazy.tsx"
    },
    "/dashboard/_sidebarLayout/category": {
      "filePath": "dashboard/_sidebarLayout/category.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/": {
      "filePath": "dashboard/_sidebarLayout/index.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/product/create": {
      "filePath": "dashboard/_sidebarLayout/product/create.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/user/create": {
      "filePath": "dashboard/_sidebarLayout/user/create.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/user/customer": {
      "filePath": "dashboard/_sidebarLayout/user/customer.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/user/employee": {
      "filePath": "dashboard/_sidebarLayout/user/employee.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/product/": {
      "filePath": "dashboard/_sidebarLayout/product/index.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/product/update/$productId": {
      "filePath": "dashboard/_sidebarLayout/product/update.$productId.tsx",
      "parent": "/dashboard/_sidebarLayout"
    },
    "/dashboard/_sidebarLayout/user/update/$userId": {
      "filePath": "dashboard/_sidebarLayout/user/update.$userId.tsx",
      "parent": "/dashboard/_sidebarLayout"
    }
  }
}
ROUTE_MANIFEST_END */
