/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSidebarLayoutRouteImport } from './routes/dashboard/_sidebarLayout'
import { Route as DashboardSidebarLayoutIndexRouteImport } from './routes/dashboard/_sidebarLayout/index'
import { Route as DashboardSidebarLayoutProfileRouteImport } from './routes/dashboard/_sidebarLayout/profile'
import { Route as DashboardSidebarLayoutPosRouteImport } from './routes/dashboard/_sidebarLayout/pos'
import { Route as DashboardSidebarLayoutOnlineOrderRouteImport } from './routes/dashboard/_sidebarLayout/online-order'
import { Route as DashboardSidebarLayoutInventoryRouteImport } from './routes/dashboard/_sidebarLayout/inventory'
import { Route as DashboardSidebarLayoutUserEmployeeRouteImport } from './routes/dashboard/_sidebarLayout/user/employee'
import { Route as DashboardSidebarLayoutUserCustomerRouteImport } from './routes/dashboard/_sidebarLayout/user/customer'
import { Route as DashboardSidebarLayoutRecipeProductRouteImport } from './routes/dashboard/_sidebarLayout/recipe/product'
import { Route as DashboardSidebarLayoutRecipeAddonRouteImport } from './routes/dashboard/_sidebarLayout/recipe/addon'
import { Route as DashboardSidebarLayoutHistoryTransactionRouteImport } from './routes/dashboard/_sidebarLayout/history/transaction'
import { Route as DashboardSidebarLayoutHistoryMyTransactionRouteImport } from './routes/dashboard/_sidebarLayout/history/my-transaction'
import { Route as DashboardSidebarLayoutHistoryInventoryUsageRouteImport } from './routes/dashboard/_sidebarLayout/history/inventory-usage'
import { Route as DashboardSidebarLayoutHistoryCateringRouteImport } from './routes/dashboard/_sidebarLayout/history/catering'
import { Route as DashboardSidebarLayoutUserUpdateUserIdRouteImport } from './routes/dashboard/_sidebarLayout/user/update.$userId'
import { Route as DashboardSidebarLayoutProductUpdateProductIdRouteImport } from './routes/dashboard/_sidebarLayout/product/update.$productId'

const DashboardRouteImport = createFileRoute('/dashboard')()
const AccessDeniedLazyRouteImport = createFileRoute('/access-denied')()
const authResetPasswordLazyRouteImport = createFileRoute(
  '/(auth)/reset-password',
)()
const authRegisterLazyRouteImport = createFileRoute('/(auth)/register')()
const authLoginLazyRouteImport = createFileRoute('/(auth)/login')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const DashboardSidebarLayoutReservationCateringLazyRouteImport =
  createFileRoute('/dashboard/_sidebarLayout/reservation-catering')()
const DashboardSidebarLayoutReservationLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/reservation',
)()
const DashboardSidebarLayoutPurchaseLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/purchase',
)()
const DashboardSidebarLayoutOperationLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/operation',
)()
const DashboardSidebarLayoutMyReservationLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/my-reservation',
)()
const DashboardSidebarLayoutInventoryOpnamesLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/inventory-opnames',
)()
const DashboardSidebarLayoutCateringPackageLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/catering-package',
)()
const DashboardSidebarLayoutCategoryLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/category',
)()
const DashboardSidebarLayoutAddonLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/addon',
)()
const DashboardSidebarLayoutProductIndexLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/product/',
)()
const DashboardSidebarLayoutUserCreateLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/user/create',
)()
const DashboardSidebarLayoutReportsRevenueLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/reports/revenue',
)()
const DashboardSidebarLayoutReportsReservationLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/reports/reservation',
)()
const DashboardSidebarLayoutReportsPurchaseLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/reports/purchase',
)()
const DashboardSidebarLayoutReportsProductSalesLazyRouteImport =
  createFileRoute('/dashboard/_sidebarLayout/reports/product-sales')()
const DashboardSidebarLayoutReportsInventoryLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/reports/inventory',
)()
const DashboardSidebarLayoutProductCreateLazyRouteImport = createFileRoute(
  '/dashboard/_sidebarLayout/product/create',
)()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedLazyRoute = AccessDeniedLazyRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/access-denied.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordLazyRoute = authResetPasswordLazyRouteImport
  .update({
    id: '/(auth)/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/reset-password.lazy').then((d) => d.Route),
  )
const authRegisterLazyRoute = authRegisterLazyRouteImport
  .update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/register.lazy').then((d) => d.Route))
const authLoginLazyRoute = authLoginLazyRouteImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const DashboardSidebarLayoutRoute = DashboardSidebarLayoutRouteImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSidebarLayoutIndexRoute =
  DashboardSidebarLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutReservationCateringLazyRoute =
  DashboardSidebarLayoutReservationCateringLazyRouteImport.update({
    id: '/reservation-catering',
    path: '/reservation-catering',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reservation-catering.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutReservationLazyRoute =
  DashboardSidebarLayoutReservationLazyRouteImport.update({
    id: '/reservation',
    path: '/reservation',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reservation.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutPurchaseLazyRoute =
  DashboardSidebarLayoutPurchaseLazyRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/purchase.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutOperationLazyRoute =
  DashboardSidebarLayoutOperationLazyRouteImport.update({
    id: '/operation',
    path: '/operation',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/operation.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutMyReservationLazyRoute =
  DashboardSidebarLayoutMyReservationLazyRouteImport.update({
    id: '/my-reservation',
    path: '/my-reservation',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/my-reservation.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutInventoryOpnamesLazyRoute =
  DashboardSidebarLayoutInventoryOpnamesLazyRouteImport.update({
    id: '/inventory-opnames',
    path: '/inventory-opnames',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/inventory-opnames.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutCateringPackageLazyRoute =
  DashboardSidebarLayoutCateringPackageLazyRouteImport.update({
    id: '/catering-package',
    path: '/catering-package',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/catering-package.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutCategoryLazyRoute =
  DashboardSidebarLayoutCategoryLazyRouteImport.update({
    id: '/category',
    path: '/category',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/category.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutAddonLazyRoute =
  DashboardSidebarLayoutAddonLazyRouteImport.update({
    id: '/addon',
    path: '/addon',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/addon.lazy').then((d) => d.Route),
  )
const DashboardSidebarLayoutProfileRoute =
  DashboardSidebarLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutPosRoute =
  DashboardSidebarLayoutPosRouteImport.update({
    id: '/pos',
    path: '/pos',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutOnlineOrderRoute =
  DashboardSidebarLayoutOnlineOrderRouteImport.update({
    id: '/online-order',
    path: '/online-order',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutInventoryRoute =
  DashboardSidebarLayoutInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutProductIndexLazyRoute =
  DashboardSidebarLayoutProductIndexLazyRouteImport.update({
    id: '/product/',
    path: '/product/',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/product/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutUserCreateLazyRoute =
  DashboardSidebarLayoutUserCreateLazyRouteImport.update({
    id: '/user/create',
    path: '/user/create',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/user/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutReportsRevenueLazyRoute =
  DashboardSidebarLayoutReportsRevenueLazyRouteImport.update({
    id: '/reports/revenue',
    path: '/reports/revenue',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reports/revenue.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutReportsReservationLazyRoute =
  DashboardSidebarLayoutReportsReservationLazyRouteImport.update({
    id: '/reports/reservation',
    path: '/reports/reservation',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reports/reservation.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutReportsPurchaseLazyRoute =
  DashboardSidebarLayoutReportsPurchaseLazyRouteImport.update({
    id: '/reports/purchase',
    path: '/reports/purchase',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reports/purchase.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutReportsProductSalesLazyRoute =
  DashboardSidebarLayoutReportsProductSalesLazyRouteImport.update({
    id: '/reports/product-sales',
    path: '/reports/product-sales',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reports/product-sales.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutReportsInventoryLazyRoute =
  DashboardSidebarLayoutReportsInventoryLazyRouteImport.update({
    id: '/reports/inventory',
    path: '/reports/inventory',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/reports/inventory.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutProductCreateLazyRoute =
  DashboardSidebarLayoutProductCreateLazyRouteImport.update({
    id: '/product/create',
    path: '/product/create',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_sidebarLayout/product/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSidebarLayoutUserEmployeeRoute =
  DashboardSidebarLayoutUserEmployeeRouteImport.update({
    id: '/user/employee',
    path: '/user/employee',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutUserCustomerRoute =
  DashboardSidebarLayoutUserCustomerRouteImport.update({
    id: '/user/customer',
    path: '/user/customer',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutRecipeProductRoute =
  DashboardSidebarLayoutRecipeProductRouteImport.update({
    id: '/recipe/product',
    path: '/recipe/product',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutRecipeAddonRoute =
  DashboardSidebarLayoutRecipeAddonRouteImport.update({
    id: '/recipe/addon',
    path: '/recipe/addon',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutHistoryTransactionRoute =
  DashboardSidebarLayoutHistoryTransactionRouteImport.update({
    id: '/history/transaction',
    path: '/history/transaction',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutHistoryMyTransactionRoute =
  DashboardSidebarLayoutHistoryMyTransactionRouteImport.update({
    id: '/history/my-transaction',
    path: '/history/my-transaction',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutHistoryInventoryUsageRoute =
  DashboardSidebarLayoutHistoryInventoryUsageRouteImport.update({
    id: '/history/inventory-usage',
    path: '/history/inventory-usage',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutHistoryCateringRoute =
  DashboardSidebarLayoutHistoryCateringRouteImport.update({
    id: '/history/catering',
    path: '/history/catering',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutUserUpdateUserIdRoute =
  DashboardSidebarLayoutUserUpdateUserIdRouteImport.update({
    id: '/user/update/$userId',
    path: '/user/update/$userId',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)
const DashboardSidebarLayoutProductUpdateProductIdRoute =
  DashboardSidebarLayoutProductUpdateProductIdRouteImport.update({
    id: '/product/update/$productId',
    path: '/product/update/$productId',
    getParentRoute: () => DashboardSidebarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedLazyRoute
  '/dashboard': typeof DashboardSidebarLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/reset-password': typeof authResetPasswordLazyRoute
  '/dashboard/inventory': typeof DashboardSidebarLayoutInventoryRoute
  '/dashboard/online-order': typeof DashboardSidebarLayoutOnlineOrderRoute
  '/dashboard/pos': typeof DashboardSidebarLayoutPosRoute
  '/dashboard/profile': typeof DashboardSidebarLayoutProfileRoute
  '/dashboard/addon': typeof DashboardSidebarLayoutAddonLazyRoute
  '/dashboard/category': typeof DashboardSidebarLayoutCategoryLazyRoute
  '/dashboard/catering-package': typeof DashboardSidebarLayoutCateringPackageLazyRoute
  '/dashboard/inventory-opnames': typeof DashboardSidebarLayoutInventoryOpnamesLazyRoute
  '/dashboard/my-reservation': typeof DashboardSidebarLayoutMyReservationLazyRoute
  '/dashboard/operation': typeof DashboardSidebarLayoutOperationLazyRoute
  '/dashboard/purchase': typeof DashboardSidebarLayoutPurchaseLazyRoute
  '/dashboard/reservation': typeof DashboardSidebarLayoutReservationLazyRoute
  '/dashboard/reservation-catering': typeof DashboardSidebarLayoutReservationCateringLazyRoute
  '/dashboard/': typeof DashboardSidebarLayoutIndexRoute
  '/dashboard/history/catering': typeof DashboardSidebarLayoutHistoryCateringRoute
  '/dashboard/history/inventory-usage': typeof DashboardSidebarLayoutHistoryInventoryUsageRoute
  '/dashboard/history/my-transaction': typeof DashboardSidebarLayoutHistoryMyTransactionRoute
  '/dashboard/history/transaction': typeof DashboardSidebarLayoutHistoryTransactionRoute
  '/dashboard/recipe/addon': typeof DashboardSidebarLayoutRecipeAddonRoute
  '/dashboard/recipe/product': typeof DashboardSidebarLayoutRecipeProductRoute
  '/dashboard/user/customer': typeof DashboardSidebarLayoutUserCustomerRoute
  '/dashboard/user/employee': typeof DashboardSidebarLayoutUserEmployeeRoute
  '/dashboard/product/create': typeof DashboardSidebarLayoutProductCreateLazyRoute
  '/dashboard/reports/inventory': typeof DashboardSidebarLayoutReportsInventoryLazyRoute
  '/dashboard/reports/product-sales': typeof DashboardSidebarLayoutReportsProductSalesLazyRoute
  '/dashboard/reports/purchase': typeof DashboardSidebarLayoutReportsPurchaseLazyRoute
  '/dashboard/reports/reservation': typeof DashboardSidebarLayoutReportsReservationLazyRoute
  '/dashboard/reports/revenue': typeof DashboardSidebarLayoutReportsRevenueLazyRoute
  '/dashboard/user/create': typeof DashboardSidebarLayoutUserCreateLazyRoute
  '/dashboard/product': typeof DashboardSidebarLayoutProductIndexLazyRoute
  '/dashboard/product/update/$productId': typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  '/dashboard/user/update/$userId': typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedLazyRoute
  '/dashboard': typeof DashboardSidebarLayoutIndexRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/reset-password': typeof authResetPasswordLazyRoute
  '/dashboard/inventory': typeof DashboardSidebarLayoutInventoryRoute
  '/dashboard/online-order': typeof DashboardSidebarLayoutOnlineOrderRoute
  '/dashboard/pos': typeof DashboardSidebarLayoutPosRoute
  '/dashboard/profile': typeof DashboardSidebarLayoutProfileRoute
  '/dashboard/addon': typeof DashboardSidebarLayoutAddonLazyRoute
  '/dashboard/category': typeof DashboardSidebarLayoutCategoryLazyRoute
  '/dashboard/catering-package': typeof DashboardSidebarLayoutCateringPackageLazyRoute
  '/dashboard/inventory-opnames': typeof DashboardSidebarLayoutInventoryOpnamesLazyRoute
  '/dashboard/my-reservation': typeof DashboardSidebarLayoutMyReservationLazyRoute
  '/dashboard/operation': typeof DashboardSidebarLayoutOperationLazyRoute
  '/dashboard/purchase': typeof DashboardSidebarLayoutPurchaseLazyRoute
  '/dashboard/reservation': typeof DashboardSidebarLayoutReservationLazyRoute
  '/dashboard/reservation-catering': typeof DashboardSidebarLayoutReservationCateringLazyRoute
  '/dashboard/history/catering': typeof DashboardSidebarLayoutHistoryCateringRoute
  '/dashboard/history/inventory-usage': typeof DashboardSidebarLayoutHistoryInventoryUsageRoute
  '/dashboard/history/my-transaction': typeof DashboardSidebarLayoutHistoryMyTransactionRoute
  '/dashboard/history/transaction': typeof DashboardSidebarLayoutHistoryTransactionRoute
  '/dashboard/recipe/addon': typeof DashboardSidebarLayoutRecipeAddonRoute
  '/dashboard/recipe/product': typeof DashboardSidebarLayoutRecipeProductRoute
  '/dashboard/user/customer': typeof DashboardSidebarLayoutUserCustomerRoute
  '/dashboard/user/employee': typeof DashboardSidebarLayoutUserEmployeeRoute
  '/dashboard/product/create': typeof DashboardSidebarLayoutProductCreateLazyRoute
  '/dashboard/reports/inventory': typeof DashboardSidebarLayoutReportsInventoryLazyRoute
  '/dashboard/reports/product-sales': typeof DashboardSidebarLayoutReportsProductSalesLazyRoute
  '/dashboard/reports/purchase': typeof DashboardSidebarLayoutReportsPurchaseLazyRoute
  '/dashboard/reports/reservation': typeof DashboardSidebarLayoutReportsReservationLazyRoute
  '/dashboard/reports/revenue': typeof DashboardSidebarLayoutReportsRevenueLazyRoute
  '/dashboard/user/create': typeof DashboardSidebarLayoutUserCreateLazyRoute
  '/dashboard/product': typeof DashboardSidebarLayoutProductIndexLazyRoute
  '/dashboard/product/update/$productId': typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  '/dashboard/user/update/$userId': typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedLazyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_sidebarLayout': typeof DashboardSidebarLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/login': typeof authLoginLazyRoute
  '/(auth)/register': typeof authRegisterLazyRoute
  '/(auth)/reset-password': typeof authResetPasswordLazyRoute
  '/dashboard/_sidebarLayout/inventory': typeof DashboardSidebarLayoutInventoryRoute
  '/dashboard/_sidebarLayout/online-order': typeof DashboardSidebarLayoutOnlineOrderRoute
  '/dashboard/_sidebarLayout/pos': typeof DashboardSidebarLayoutPosRoute
  '/dashboard/_sidebarLayout/profile': typeof DashboardSidebarLayoutProfileRoute
  '/dashboard/_sidebarLayout/addon': typeof DashboardSidebarLayoutAddonLazyRoute
  '/dashboard/_sidebarLayout/category': typeof DashboardSidebarLayoutCategoryLazyRoute
  '/dashboard/_sidebarLayout/catering-package': typeof DashboardSidebarLayoutCateringPackageLazyRoute
  '/dashboard/_sidebarLayout/inventory-opnames': typeof DashboardSidebarLayoutInventoryOpnamesLazyRoute
  '/dashboard/_sidebarLayout/my-reservation': typeof DashboardSidebarLayoutMyReservationLazyRoute
  '/dashboard/_sidebarLayout/operation': typeof DashboardSidebarLayoutOperationLazyRoute
  '/dashboard/_sidebarLayout/purchase': typeof DashboardSidebarLayoutPurchaseLazyRoute
  '/dashboard/_sidebarLayout/reservation': typeof DashboardSidebarLayoutReservationLazyRoute
  '/dashboard/_sidebarLayout/reservation-catering': typeof DashboardSidebarLayoutReservationCateringLazyRoute
  '/dashboard/_sidebarLayout/': typeof DashboardSidebarLayoutIndexRoute
  '/dashboard/_sidebarLayout/history/catering': typeof DashboardSidebarLayoutHistoryCateringRoute
  '/dashboard/_sidebarLayout/history/inventory-usage': typeof DashboardSidebarLayoutHistoryInventoryUsageRoute
  '/dashboard/_sidebarLayout/history/my-transaction': typeof DashboardSidebarLayoutHistoryMyTransactionRoute
  '/dashboard/_sidebarLayout/history/transaction': typeof DashboardSidebarLayoutHistoryTransactionRoute
  '/dashboard/_sidebarLayout/recipe/addon': typeof DashboardSidebarLayoutRecipeAddonRoute
  '/dashboard/_sidebarLayout/recipe/product': typeof DashboardSidebarLayoutRecipeProductRoute
  '/dashboard/_sidebarLayout/user/customer': typeof DashboardSidebarLayoutUserCustomerRoute
  '/dashboard/_sidebarLayout/user/employee': typeof DashboardSidebarLayoutUserEmployeeRoute
  '/dashboard/_sidebarLayout/product/create': typeof DashboardSidebarLayoutProductCreateLazyRoute
  '/dashboard/_sidebarLayout/reports/inventory': typeof DashboardSidebarLayoutReportsInventoryLazyRoute
  '/dashboard/_sidebarLayout/reports/product-sales': typeof DashboardSidebarLayoutReportsProductSalesLazyRoute
  '/dashboard/_sidebarLayout/reports/purchase': typeof DashboardSidebarLayoutReportsPurchaseLazyRoute
  '/dashboard/_sidebarLayout/reports/reservation': typeof DashboardSidebarLayoutReportsReservationLazyRoute
  '/dashboard/_sidebarLayout/reports/revenue': typeof DashboardSidebarLayoutReportsRevenueLazyRoute
  '/dashboard/_sidebarLayout/user/create': typeof DashboardSidebarLayoutUserCreateLazyRoute
  '/dashboard/_sidebarLayout/product/': typeof DashboardSidebarLayoutProductIndexLazyRoute
  '/dashboard/_sidebarLayout/product/update/$productId': typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  '/dashboard/_sidebarLayout/user/update/$userId': typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/inventory'
    | '/dashboard/online-order'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/addon'
    | '/dashboard/category'
    | '/dashboard/catering-package'
    | '/dashboard/inventory-opnames'
    | '/dashboard/my-reservation'
    | '/dashboard/operation'
    | '/dashboard/purchase'
    | '/dashboard/reservation'
    | '/dashboard/reservation-catering'
    | '/dashboard/'
    | '/dashboard/history/catering'
    | '/dashboard/history/inventory-usage'
    | '/dashboard/history/my-transaction'
    | '/dashboard/history/transaction'
    | '/dashboard/recipe/addon'
    | '/dashboard/recipe/product'
    | '/dashboard/user/customer'
    | '/dashboard/user/employee'
    | '/dashboard/product/create'
    | '/dashboard/reports/inventory'
    | '/dashboard/reports/product-sales'
    | '/dashboard/reports/purchase'
    | '/dashboard/reports/reservation'
    | '/dashboard/reports/revenue'
    | '/dashboard/user/create'
    | '/dashboard/product'
    | '/dashboard/product/update/$productId'
    | '/dashboard/user/update/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/inventory'
    | '/dashboard/online-order'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/addon'
    | '/dashboard/category'
    | '/dashboard/catering-package'
    | '/dashboard/inventory-opnames'
    | '/dashboard/my-reservation'
    | '/dashboard/operation'
    | '/dashboard/purchase'
    | '/dashboard/reservation'
    | '/dashboard/reservation-catering'
    | '/dashboard/history/catering'
    | '/dashboard/history/inventory-usage'
    | '/dashboard/history/my-transaction'
    | '/dashboard/history/transaction'
    | '/dashboard/recipe/addon'
    | '/dashboard/recipe/product'
    | '/dashboard/user/customer'
    | '/dashboard/user/employee'
    | '/dashboard/product/create'
    | '/dashboard/reports/inventory'
    | '/dashboard/reports/product-sales'
    | '/dashboard/reports/purchase'
    | '/dashboard/reports/reservation'
    | '/dashboard/reports/revenue'
    | '/dashboard/user/create'
    | '/dashboard/product'
    | '/dashboard/product/update/$productId'
    | '/dashboard/user/update/$userId'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/dashboard'
    | '/dashboard/_sidebarLayout'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/dashboard/_sidebarLayout/inventory'
    | '/dashboard/_sidebarLayout/online-order'
    | '/dashboard/_sidebarLayout/pos'
    | '/dashboard/_sidebarLayout/profile'
    | '/dashboard/_sidebarLayout/addon'
    | '/dashboard/_sidebarLayout/category'
    | '/dashboard/_sidebarLayout/catering-package'
    | '/dashboard/_sidebarLayout/inventory-opnames'
    | '/dashboard/_sidebarLayout/my-reservation'
    | '/dashboard/_sidebarLayout/operation'
    | '/dashboard/_sidebarLayout/purchase'
    | '/dashboard/_sidebarLayout/reservation'
    | '/dashboard/_sidebarLayout/reservation-catering'
    | '/dashboard/_sidebarLayout/'
    | '/dashboard/_sidebarLayout/history/catering'
    | '/dashboard/_sidebarLayout/history/inventory-usage'
    | '/dashboard/_sidebarLayout/history/my-transaction'
    | '/dashboard/_sidebarLayout/history/transaction'
    | '/dashboard/_sidebarLayout/recipe/addon'
    | '/dashboard/_sidebarLayout/recipe/product'
    | '/dashboard/_sidebarLayout/user/customer'
    | '/dashboard/_sidebarLayout/user/employee'
    | '/dashboard/_sidebarLayout/product/create'
    | '/dashboard/_sidebarLayout/reports/inventory'
    | '/dashboard/_sidebarLayout/reports/product-sales'
    | '/dashboard/_sidebarLayout/reports/purchase'
    | '/dashboard/_sidebarLayout/reports/reservation'
    | '/dashboard/_sidebarLayout/reports/revenue'
    | '/dashboard/_sidebarLayout/user/create'
    | '/dashboard/_sidebarLayout/product/'
    | '/dashboard/_sidebarLayout/product/update/$productId'
    | '/dashboard/_sidebarLayout/user/update/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedLazyRoute: typeof AccessDeniedLazyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authLoginLazyRoute: typeof authLoginLazyRoute
  authRegisterLazyRoute: typeof authRegisterLazyRoute
  authResetPasswordLazyRoute: typeof authResetPasswordLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_sidebarLayout': {
      id: '/dashboard/_sidebarLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardSidebarLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_sidebarLayout/': {
      id: '/dashboard/_sidebarLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardSidebarLayoutIndexRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reservation-catering': {
      id: '/dashboard/_sidebarLayout/reservation-catering'
      path: '/reservation-catering'
      fullPath: '/dashboard/reservation-catering'
      preLoaderRoute: typeof DashboardSidebarLayoutReservationCateringLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reservation': {
      id: '/dashboard/_sidebarLayout/reservation'
      path: '/reservation'
      fullPath: '/dashboard/reservation'
      preLoaderRoute: typeof DashboardSidebarLayoutReservationLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/purchase': {
      id: '/dashboard/_sidebarLayout/purchase'
      path: '/purchase'
      fullPath: '/dashboard/purchase'
      preLoaderRoute: typeof DashboardSidebarLayoutPurchaseLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/operation': {
      id: '/dashboard/_sidebarLayout/operation'
      path: '/operation'
      fullPath: '/dashboard/operation'
      preLoaderRoute: typeof DashboardSidebarLayoutOperationLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/my-reservation': {
      id: '/dashboard/_sidebarLayout/my-reservation'
      path: '/my-reservation'
      fullPath: '/dashboard/my-reservation'
      preLoaderRoute: typeof DashboardSidebarLayoutMyReservationLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/inventory-opnames': {
      id: '/dashboard/_sidebarLayout/inventory-opnames'
      path: '/inventory-opnames'
      fullPath: '/dashboard/inventory-opnames'
      preLoaderRoute: typeof DashboardSidebarLayoutInventoryOpnamesLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/catering-package': {
      id: '/dashboard/_sidebarLayout/catering-package'
      path: '/catering-package'
      fullPath: '/dashboard/catering-package'
      preLoaderRoute: typeof DashboardSidebarLayoutCateringPackageLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/category': {
      id: '/dashboard/_sidebarLayout/category'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardSidebarLayoutCategoryLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/addon': {
      id: '/dashboard/_sidebarLayout/addon'
      path: '/addon'
      fullPath: '/dashboard/addon'
      preLoaderRoute: typeof DashboardSidebarLayoutAddonLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/profile': {
      id: '/dashboard/_sidebarLayout/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardSidebarLayoutProfileRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/pos': {
      id: '/dashboard/_sidebarLayout/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof DashboardSidebarLayoutPosRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/online-order': {
      id: '/dashboard/_sidebarLayout/online-order'
      path: '/online-order'
      fullPath: '/dashboard/online-order'
      preLoaderRoute: typeof DashboardSidebarLayoutOnlineOrderRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/inventory': {
      id: '/dashboard/_sidebarLayout/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardSidebarLayoutInventoryRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/product/': {
      id: '/dashboard/_sidebarLayout/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardSidebarLayoutProductIndexLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/user/create': {
      id: '/dashboard/_sidebarLayout/user/create'
      path: '/user/create'
      fullPath: '/dashboard/user/create'
      preLoaderRoute: typeof DashboardSidebarLayoutUserCreateLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reports/revenue': {
      id: '/dashboard/_sidebarLayout/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/dashboard/reports/revenue'
      preLoaderRoute: typeof DashboardSidebarLayoutReportsRevenueLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reports/reservation': {
      id: '/dashboard/_sidebarLayout/reports/reservation'
      path: '/reports/reservation'
      fullPath: '/dashboard/reports/reservation'
      preLoaderRoute: typeof DashboardSidebarLayoutReportsReservationLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reports/purchase': {
      id: '/dashboard/_sidebarLayout/reports/purchase'
      path: '/reports/purchase'
      fullPath: '/dashboard/reports/purchase'
      preLoaderRoute: typeof DashboardSidebarLayoutReportsPurchaseLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reports/product-sales': {
      id: '/dashboard/_sidebarLayout/reports/product-sales'
      path: '/reports/product-sales'
      fullPath: '/dashboard/reports/product-sales'
      preLoaderRoute: typeof DashboardSidebarLayoutReportsProductSalesLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/reports/inventory': {
      id: '/dashboard/_sidebarLayout/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/dashboard/reports/inventory'
      preLoaderRoute: typeof DashboardSidebarLayoutReportsInventoryLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/product/create': {
      id: '/dashboard/_sidebarLayout/product/create'
      path: '/product/create'
      fullPath: '/dashboard/product/create'
      preLoaderRoute: typeof DashboardSidebarLayoutProductCreateLazyRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/user/employee': {
      id: '/dashboard/_sidebarLayout/user/employee'
      path: '/user/employee'
      fullPath: '/dashboard/user/employee'
      preLoaderRoute: typeof DashboardSidebarLayoutUserEmployeeRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/user/customer': {
      id: '/dashboard/_sidebarLayout/user/customer'
      path: '/user/customer'
      fullPath: '/dashboard/user/customer'
      preLoaderRoute: typeof DashboardSidebarLayoutUserCustomerRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/recipe/product': {
      id: '/dashboard/_sidebarLayout/recipe/product'
      path: '/recipe/product'
      fullPath: '/dashboard/recipe/product'
      preLoaderRoute: typeof DashboardSidebarLayoutRecipeProductRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/recipe/addon': {
      id: '/dashboard/_sidebarLayout/recipe/addon'
      path: '/recipe/addon'
      fullPath: '/dashboard/recipe/addon'
      preLoaderRoute: typeof DashboardSidebarLayoutRecipeAddonRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/history/transaction': {
      id: '/dashboard/_sidebarLayout/history/transaction'
      path: '/history/transaction'
      fullPath: '/dashboard/history/transaction'
      preLoaderRoute: typeof DashboardSidebarLayoutHistoryTransactionRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/history/my-transaction': {
      id: '/dashboard/_sidebarLayout/history/my-transaction'
      path: '/history/my-transaction'
      fullPath: '/dashboard/history/my-transaction'
      preLoaderRoute: typeof DashboardSidebarLayoutHistoryMyTransactionRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/history/inventory-usage': {
      id: '/dashboard/_sidebarLayout/history/inventory-usage'
      path: '/history/inventory-usage'
      fullPath: '/dashboard/history/inventory-usage'
      preLoaderRoute: typeof DashboardSidebarLayoutHistoryInventoryUsageRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/history/catering': {
      id: '/dashboard/_sidebarLayout/history/catering'
      path: '/history/catering'
      fullPath: '/dashboard/history/catering'
      preLoaderRoute: typeof DashboardSidebarLayoutHistoryCateringRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/user/update/$userId': {
      id: '/dashboard/_sidebarLayout/user/update/$userId'
      path: '/user/update/$userId'
      fullPath: '/dashboard/user/update/$userId'
      preLoaderRoute: typeof DashboardSidebarLayoutUserUpdateUserIdRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
    '/dashboard/_sidebarLayout/product/update/$productId': {
      id: '/dashboard/_sidebarLayout/product/update/$productId'
      path: '/product/update/$productId'
      fullPath: '/dashboard/product/update/$productId'
      preLoaderRoute: typeof DashboardSidebarLayoutProductUpdateProductIdRouteImport
      parentRoute: typeof DashboardSidebarLayoutRoute
    }
  }
}

interface DashboardSidebarLayoutRouteChildren {
  DashboardSidebarLayoutInventoryRoute: typeof DashboardSidebarLayoutInventoryRoute
  DashboardSidebarLayoutOnlineOrderRoute: typeof DashboardSidebarLayoutOnlineOrderRoute
  DashboardSidebarLayoutPosRoute: typeof DashboardSidebarLayoutPosRoute
  DashboardSidebarLayoutProfileRoute: typeof DashboardSidebarLayoutProfileRoute
  DashboardSidebarLayoutAddonLazyRoute: typeof DashboardSidebarLayoutAddonLazyRoute
  DashboardSidebarLayoutCategoryLazyRoute: typeof DashboardSidebarLayoutCategoryLazyRoute
  DashboardSidebarLayoutCateringPackageLazyRoute: typeof DashboardSidebarLayoutCateringPackageLazyRoute
  DashboardSidebarLayoutInventoryOpnamesLazyRoute: typeof DashboardSidebarLayoutInventoryOpnamesLazyRoute
  DashboardSidebarLayoutMyReservationLazyRoute: typeof DashboardSidebarLayoutMyReservationLazyRoute
  DashboardSidebarLayoutOperationLazyRoute: typeof DashboardSidebarLayoutOperationLazyRoute
  DashboardSidebarLayoutPurchaseLazyRoute: typeof DashboardSidebarLayoutPurchaseLazyRoute
  DashboardSidebarLayoutReservationLazyRoute: typeof DashboardSidebarLayoutReservationLazyRoute
  DashboardSidebarLayoutReservationCateringLazyRoute: typeof DashboardSidebarLayoutReservationCateringLazyRoute
  DashboardSidebarLayoutIndexRoute: typeof DashboardSidebarLayoutIndexRoute
  DashboardSidebarLayoutHistoryCateringRoute: typeof DashboardSidebarLayoutHistoryCateringRoute
  DashboardSidebarLayoutHistoryInventoryUsageRoute: typeof DashboardSidebarLayoutHistoryInventoryUsageRoute
  DashboardSidebarLayoutHistoryMyTransactionRoute: typeof DashboardSidebarLayoutHistoryMyTransactionRoute
  DashboardSidebarLayoutHistoryTransactionRoute: typeof DashboardSidebarLayoutHistoryTransactionRoute
  DashboardSidebarLayoutRecipeAddonRoute: typeof DashboardSidebarLayoutRecipeAddonRoute
  DashboardSidebarLayoutRecipeProductRoute: typeof DashboardSidebarLayoutRecipeProductRoute
  DashboardSidebarLayoutUserCustomerRoute: typeof DashboardSidebarLayoutUserCustomerRoute
  DashboardSidebarLayoutUserEmployeeRoute: typeof DashboardSidebarLayoutUserEmployeeRoute
  DashboardSidebarLayoutProductCreateLazyRoute: typeof DashboardSidebarLayoutProductCreateLazyRoute
  DashboardSidebarLayoutReportsInventoryLazyRoute: typeof DashboardSidebarLayoutReportsInventoryLazyRoute
  DashboardSidebarLayoutReportsProductSalesLazyRoute: typeof DashboardSidebarLayoutReportsProductSalesLazyRoute
  DashboardSidebarLayoutReportsPurchaseLazyRoute: typeof DashboardSidebarLayoutReportsPurchaseLazyRoute
  DashboardSidebarLayoutReportsReservationLazyRoute: typeof DashboardSidebarLayoutReportsReservationLazyRoute
  DashboardSidebarLayoutReportsRevenueLazyRoute: typeof DashboardSidebarLayoutReportsRevenueLazyRoute
  DashboardSidebarLayoutUserCreateLazyRoute: typeof DashboardSidebarLayoutUserCreateLazyRoute
  DashboardSidebarLayoutProductIndexLazyRoute: typeof DashboardSidebarLayoutProductIndexLazyRoute
  DashboardSidebarLayoutProductUpdateProductIdRoute: typeof DashboardSidebarLayoutProductUpdateProductIdRoute
  DashboardSidebarLayoutUserUpdateUserIdRoute: typeof DashboardSidebarLayoutUserUpdateUserIdRoute
}

const DashboardSidebarLayoutRouteChildren: DashboardSidebarLayoutRouteChildren =
  {
    DashboardSidebarLayoutInventoryRoute: DashboardSidebarLayoutInventoryRoute,
    DashboardSidebarLayoutOnlineOrderRoute:
      DashboardSidebarLayoutOnlineOrderRoute,
    DashboardSidebarLayoutPosRoute: DashboardSidebarLayoutPosRoute,
    DashboardSidebarLayoutProfileRoute: DashboardSidebarLayoutProfileRoute,
    DashboardSidebarLayoutAddonLazyRoute: DashboardSidebarLayoutAddonLazyRoute,
    DashboardSidebarLayoutCategoryLazyRoute:
      DashboardSidebarLayoutCategoryLazyRoute,
    DashboardSidebarLayoutCateringPackageLazyRoute:
      DashboardSidebarLayoutCateringPackageLazyRoute,
    DashboardSidebarLayoutInventoryOpnamesLazyRoute:
      DashboardSidebarLayoutInventoryOpnamesLazyRoute,
    DashboardSidebarLayoutMyReservationLazyRoute:
      DashboardSidebarLayoutMyReservationLazyRoute,
    DashboardSidebarLayoutOperationLazyRoute:
      DashboardSidebarLayoutOperationLazyRoute,
    DashboardSidebarLayoutPurchaseLazyRoute:
      DashboardSidebarLayoutPurchaseLazyRoute,
    DashboardSidebarLayoutReservationLazyRoute:
      DashboardSidebarLayoutReservationLazyRoute,
    DashboardSidebarLayoutReservationCateringLazyRoute:
      DashboardSidebarLayoutReservationCateringLazyRoute,
    DashboardSidebarLayoutIndexRoute: DashboardSidebarLayoutIndexRoute,
    DashboardSidebarLayoutHistoryCateringRoute:
      DashboardSidebarLayoutHistoryCateringRoute,
    DashboardSidebarLayoutHistoryInventoryUsageRoute:
      DashboardSidebarLayoutHistoryInventoryUsageRoute,
    DashboardSidebarLayoutHistoryMyTransactionRoute:
      DashboardSidebarLayoutHistoryMyTransactionRoute,
    DashboardSidebarLayoutHistoryTransactionRoute:
      DashboardSidebarLayoutHistoryTransactionRoute,
    DashboardSidebarLayoutRecipeAddonRoute:
      DashboardSidebarLayoutRecipeAddonRoute,
    DashboardSidebarLayoutRecipeProductRoute:
      DashboardSidebarLayoutRecipeProductRoute,
    DashboardSidebarLayoutUserCustomerRoute:
      DashboardSidebarLayoutUserCustomerRoute,
    DashboardSidebarLayoutUserEmployeeRoute:
      DashboardSidebarLayoutUserEmployeeRoute,
    DashboardSidebarLayoutProductCreateLazyRoute:
      DashboardSidebarLayoutProductCreateLazyRoute,
    DashboardSidebarLayoutReportsInventoryLazyRoute:
      DashboardSidebarLayoutReportsInventoryLazyRoute,
    DashboardSidebarLayoutReportsProductSalesLazyRoute:
      DashboardSidebarLayoutReportsProductSalesLazyRoute,
    DashboardSidebarLayoutReportsPurchaseLazyRoute:
      DashboardSidebarLayoutReportsPurchaseLazyRoute,
    DashboardSidebarLayoutReportsReservationLazyRoute:
      DashboardSidebarLayoutReportsReservationLazyRoute,
    DashboardSidebarLayoutReportsRevenueLazyRoute:
      DashboardSidebarLayoutReportsRevenueLazyRoute,
    DashboardSidebarLayoutUserCreateLazyRoute:
      DashboardSidebarLayoutUserCreateLazyRoute,
    DashboardSidebarLayoutProductIndexLazyRoute:
      DashboardSidebarLayoutProductIndexLazyRoute,
    DashboardSidebarLayoutProductUpdateProductIdRoute:
      DashboardSidebarLayoutProductUpdateProductIdRoute,
    DashboardSidebarLayoutUserUpdateUserIdRoute:
      DashboardSidebarLayoutUserUpdateUserIdRoute,
  }

const DashboardSidebarLayoutRouteWithChildren =
  DashboardSidebarLayoutRoute._addFileChildren(
    DashboardSidebarLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardSidebarLayoutRoute: typeof DashboardSidebarLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSidebarLayoutRoute: DashboardSidebarLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedLazyRoute: AccessDeniedLazyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authLoginLazyRoute: authLoginLazyRoute,
  authRegisterLazyRoute: authRegisterLazyRoute,
  authResetPasswordLazyRoute: authResetPasswordLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
